Name: Zeon
IconPath: dekat.png
SoundPath: dekat.wav
Description: |
    Equipe de Zaku de Zeon venu défoncer du Gundam, ZIEG ZEON!
BrainsPackage: inGameTeams.python_teamFunction_level_0
ScriptImplementation: python
AgentsBrainClasses:
    WarBase: WarBase.py
    WarExplorer: WarExplorer.py
    WarRocketLauncher: WarRocketLauncher.py
    WarKamikaze: WarKamikaze.py
    WarEngineer: WarEngineer.py
    WarTurret: WarTurret.py
    
